//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _18
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TennisEntities : DbContext
    {
        public TennisEntities()
            : base("name=TennisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tenni> Tennis { get; set; }
        //Добавляем статичную ссылку на контекст
        private static TennisEntities context;
        //Добавляем метод получения ссылки на контекст
        public static TennisEntities GetContext()
        {
            if (context == null)
                context = new TennisEntities();
            return context;
        }
    }
}
