//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _18
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenni
    {
        public int Number { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string Gender { get; set; }
        public int YearOfBirth { get; set; }
        public string SurnameTrainer { get; set; }
        public string NameTrainer { get; set; }
        public string PatronymicTrainer { get; set; }
        public string Country { get; set; }
        public int Rating1 { get; set; }
        public Nullable<int> Rating2 { get; set; }
        public Nullable<int> Rating3 { get; set; }
        public Nullable<int> Rating4 { get; set; }
        public Nullable<int> Rating5 { get; set; }
    }
}
